package com.arz.pmp.base.entity;

/**
 * Database Table Remarks:
 *   课程信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pmp_course
 */
public class PmpCourseEntity {
    /**
     * Database Column Remarks:
     *   课程信息表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_course.course_id
     *
     * @mbg.generated
     */
    private Long courseId;

    /**
     * Database Column Remarks:
     *   课程名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_course.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_course.course_desc
     *
     * @mbg.generated
     */
    private String courseDesc;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_course.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   是否启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_course.use_on
     *
     * @mbg.generated
     */
    private Boolean useOn;

    /**
     * Database Column Remarks:
     *   删除状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_course.del_on
     *
     * @mbg.generated
     */
    private Boolean delOn;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_course.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_course.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_course.create_manager
     *
     * @mbg.generated
     */
    private Long createManager;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_course.update_manager
     *
     * @mbg.generated
     */
    private Long updateManager;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_course.course_id
     *
     * @return the value of pmp_course.course_id
     *
     * @mbg.generated
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_course.course_id
     *
     * @param courseId the value for pmp_course.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_course.course_name
     *
     * @return the value of pmp_course.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_course.course_name
     *
     * @param courseName the value for pmp_course.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_course.course_desc
     *
     * @return the value of pmp_course.course_desc
     *
     * @mbg.generated
     */
    public String getCourseDesc() {
        return courseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_course.course_desc
     *
     * @param courseDesc the value for pmp_course.course_desc
     *
     * @mbg.generated
     */
    public void setCourseDesc(String courseDesc) {
        this.courseDesc = courseDesc == null ? null : courseDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_course.sort
     *
     * @return the value of pmp_course.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_course.sort
     *
     * @param sort the value for pmp_course.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_course.use_on
     *
     * @return the value of pmp_course.use_on
     *
     * @mbg.generated
     */
    public Boolean getUseOn() {
        return useOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_course.use_on
     *
     * @param useOn the value for pmp_course.use_on
     *
     * @mbg.generated
     */
    public void setUseOn(Boolean useOn) {
        this.useOn = useOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_course.del_on
     *
     * @return the value of pmp_course.del_on
     *
     * @mbg.generated
     */
    public Boolean getDelOn() {
        return delOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_course.del_on
     *
     * @param delOn the value for pmp_course.del_on
     *
     * @mbg.generated
     */
    public void setDelOn(Boolean delOn) {
        this.delOn = delOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_course.create_time
     *
     * @return the value of pmp_course.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_course.create_time
     *
     * @param createTime the value for pmp_course.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_course.update_time
     *
     * @return the value of pmp_course.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_course.update_time
     *
     * @param updateTime the value for pmp_course.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_course.create_manager
     *
     * @return the value of pmp_course.create_manager
     *
     * @mbg.generated
     */
    public Long getCreateManager() {
        return createManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_course.create_manager
     *
     * @param createManager the value for pmp_course.create_manager
     *
     * @mbg.generated
     */
    public void setCreateManager(Long createManager) {
        this.createManager = createManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_course.update_manager
     *
     * @return the value of pmp_course.update_manager
     *
     * @mbg.generated
     */
    public Long getUpdateManager() {
        return updateManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_course.update_manager
     *
     * @param updateManager the value for pmp_course.update_manager
     *
     * @mbg.generated
     */
    public void setUpdateManager(Long updateManager) {
        this.updateManager = updateManager;
    }
}