package com.arz.pmp.base.entity;

/**
 * Database Table Remarks:
 *   教学点信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pmp_teaching_place
 */
public class PmpTeachingPlaceEntity {
    /**
     * Database Column Remarks:
     *   教学点信息表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.place_id
     *
     * @mbg.generated
     */
    private Long placeId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.place_name
     *
     * @mbg.generated
     */
    private String placeName;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.place_desc
     *
     * @mbg.generated
     */
    private String placeDesc;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   联系人名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.contact_name
     *
     * @mbg.generated
     */
    private String contactName;

    /**
     * Database Column Remarks:
     *   联系手机/座机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.contact_phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   是否使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.use_on
     *
     * @mbg.generated
     */
    private Boolean useOn;

    /**
     * Database Column Remarks:
     *   删除状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.del_on
     *
     * @mbg.generated
     */
    private Boolean delOn;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.create_manager
     *
     * @mbg.generated
     */
    private Long createManager;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_place.update_manager
     *
     * @mbg.generated
     */
    private Long updateManager;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.place_id
     *
     * @return the value of pmp_teaching_place.place_id
     *
     * @mbg.generated
     */
    public Long getPlaceId() {
        return placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.place_id
     *
     * @param placeId the value for pmp_teaching_place.place_id
     *
     * @mbg.generated
     */
    public void setPlaceId(Long placeId) {
        this.placeId = placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.place_name
     *
     * @return the value of pmp_teaching_place.place_name
     *
     * @mbg.generated
     */
    public String getPlaceName() {
        return placeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.place_name
     *
     * @param placeName the value for pmp_teaching_place.place_name
     *
     * @mbg.generated
     */
    public void setPlaceName(String placeName) {
        this.placeName = placeName == null ? null : placeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.place_desc
     *
     * @return the value of pmp_teaching_place.place_desc
     *
     * @mbg.generated
     */
    public String getPlaceDesc() {
        return placeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.place_desc
     *
     * @param placeDesc the value for pmp_teaching_place.place_desc
     *
     * @mbg.generated
     */
    public void setPlaceDesc(String placeDesc) {
        this.placeDesc = placeDesc == null ? null : placeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.address
     *
     * @return the value of pmp_teaching_place.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.address
     *
     * @param address the value for pmp_teaching_place.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.contact_name
     *
     * @return the value of pmp_teaching_place.contact_name
     *
     * @mbg.generated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.contact_name
     *
     * @param contactName the value for pmp_teaching_place.contact_name
     *
     * @mbg.generated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.contact_phone
     *
     * @return the value of pmp_teaching_place.contact_phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.contact_phone
     *
     * @param contactPhone the value for pmp_teaching_place.contact_phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.sort
     *
     * @return the value of pmp_teaching_place.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.sort
     *
     * @param sort the value for pmp_teaching_place.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.use_on
     *
     * @return the value of pmp_teaching_place.use_on
     *
     * @mbg.generated
     */
    public Boolean getUseOn() {
        return useOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.use_on
     *
     * @param useOn the value for pmp_teaching_place.use_on
     *
     * @mbg.generated
     */
    public void setUseOn(Boolean useOn) {
        this.useOn = useOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.del_on
     *
     * @return the value of pmp_teaching_place.del_on
     *
     * @mbg.generated
     */
    public Boolean getDelOn() {
        return delOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.del_on
     *
     * @param delOn the value for pmp_teaching_place.del_on
     *
     * @mbg.generated
     */
    public void setDelOn(Boolean delOn) {
        this.delOn = delOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.create_time
     *
     * @return the value of pmp_teaching_place.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.create_time
     *
     * @param createTime the value for pmp_teaching_place.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.update_time
     *
     * @return the value of pmp_teaching_place.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.update_time
     *
     * @param updateTime the value for pmp_teaching_place.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.create_manager
     *
     * @return the value of pmp_teaching_place.create_manager
     *
     * @mbg.generated
     */
    public Long getCreateManager() {
        return createManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.create_manager
     *
     * @param createManager the value for pmp_teaching_place.create_manager
     *
     * @mbg.generated
     */
    public void setCreateManager(Long createManager) {
        this.createManager = createManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_place.update_manager
     *
     * @return the value of pmp_teaching_place.update_manager
     *
     * @mbg.generated
     */
    public Long getUpdateManager() {
        return updateManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_place.update_manager
     *
     * @param updateManager the value for pmp_teaching_place.update_manager
     *
     * @mbg.generated
     */
    public void setUpdateManager(Long updateManager) {
        this.updateManager = updateManager;
    }
}