package com.arz.pmp.base.entity;

/**
 * Database Table Remarks:
 *   课程开班教学类型表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pmp_teaching_type
 */
public class PmpTeachingTypeEntity {
    /**
     * Database Column Remarks:
     *   课程开班教学类型表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_type.type_id
     *
     * @mbg.generated
     */
    private Long typeId;

    /**
     * Database Column Remarks:
     *   类型名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_type.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_type.type_desc
     *
     * @mbg.generated
     */
    private String typeDesc;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_type.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_type.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_type.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_type.create_manager
     *
     * @mbg.generated
     */
    private Long createManager;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_type.update_manager
     *
     * @mbg.generated
     */
    private Long updateManager;

    /**
     * Database Column Remarks:
     *   删除状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_teaching_type.del_on
     *
     * @mbg.generated
     */
    private Boolean delOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_type.type_id
     *
     * @return the value of pmp_teaching_type.type_id
     *
     * @mbg.generated
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_type.type_id
     *
     * @param typeId the value for pmp_teaching_type.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_type.type_name
     *
     * @return the value of pmp_teaching_type.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_type.type_name
     *
     * @param typeName the value for pmp_teaching_type.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_type.type_desc
     *
     * @return the value of pmp_teaching_type.type_desc
     *
     * @mbg.generated
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_type.type_desc
     *
     * @param typeDesc the value for pmp_teaching_type.type_desc
     *
     * @mbg.generated
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc == null ? null : typeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_type.sort
     *
     * @return the value of pmp_teaching_type.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_type.sort
     *
     * @param sort the value for pmp_teaching_type.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_type.create_time
     *
     * @return the value of pmp_teaching_type.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_type.create_time
     *
     * @param createTime the value for pmp_teaching_type.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_type.update_time
     *
     * @return the value of pmp_teaching_type.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_type.update_time
     *
     * @param updateTime the value for pmp_teaching_type.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_type.create_manager
     *
     * @return the value of pmp_teaching_type.create_manager
     *
     * @mbg.generated
     */
    public Long getCreateManager() {
        return createManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_type.create_manager
     *
     * @param createManager the value for pmp_teaching_type.create_manager
     *
     * @mbg.generated
     */
    public void setCreateManager(Long createManager) {
        this.createManager = createManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_type.update_manager
     *
     * @return the value of pmp_teaching_type.update_manager
     *
     * @mbg.generated
     */
    public Long getUpdateManager() {
        return updateManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_type.update_manager
     *
     * @param updateManager the value for pmp_teaching_type.update_manager
     *
     * @mbg.generated
     */
    public void setUpdateManager(Long updateManager) {
        this.updateManager = updateManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_teaching_type.del_on
     *
     * @return the value of pmp_teaching_type.del_on
     *
     * @mbg.generated
     */
    public Boolean getDelOn() {
        return delOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_teaching_type.del_on
     *
     * @param delOn the value for pmp_teaching_type.del_on
     *
     * @mbg.generated
     */
    public void setDelOn(Boolean delOn) {
        this.delOn = delOn;
    }
}