package com.arz.pmp.base.entity;

/**
 * Database Table Remarks:
 *   学历信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pmp_user_education
 */
public class PmpUserEducationEntity {
    /**
     * Database Column Remarks:
     *   学历信息表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user_education.education_id
     *
     * @mbg.generated
     */
    private Long educationId;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user_education.education_name
     *
     * @mbg.generated
     */
    private String educationName;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user_education.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user_education.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user_education.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user_education.create_manager
     *
     * @mbg.generated
     */
    private Long createManager;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user_education.update_manager
     *
     * @mbg.generated
     */
    private Long updateManager;

    /**
     * Database Column Remarks:
     *   删除状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user_education.del_on
     *
     * @mbg.generated
     */
    private Boolean delOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user_education.education_id
     *
     * @return the value of pmp_user_education.education_id
     *
     * @mbg.generated
     */
    public Long getEducationId() {
        return educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user_education.education_id
     *
     * @param educationId the value for pmp_user_education.education_id
     *
     * @mbg.generated
     */
    public void setEducationId(Long educationId) {
        this.educationId = educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user_education.education_name
     *
     * @return the value of pmp_user_education.education_name
     *
     * @mbg.generated
     */
    public String getEducationName() {
        return educationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user_education.education_name
     *
     * @param educationName the value for pmp_user_education.education_name
     *
     * @mbg.generated
     */
    public void setEducationName(String educationName) {
        this.educationName = educationName == null ? null : educationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user_education.sort
     *
     * @return the value of pmp_user_education.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user_education.sort
     *
     * @param sort the value for pmp_user_education.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user_education.create_time
     *
     * @return the value of pmp_user_education.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user_education.create_time
     *
     * @param createTime the value for pmp_user_education.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user_education.update_time
     *
     * @return the value of pmp_user_education.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user_education.update_time
     *
     * @param updateTime the value for pmp_user_education.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user_education.create_manager
     *
     * @return the value of pmp_user_education.create_manager
     *
     * @mbg.generated
     */
    public Long getCreateManager() {
        return createManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user_education.create_manager
     *
     * @param createManager the value for pmp_user_education.create_manager
     *
     * @mbg.generated
     */
    public void setCreateManager(Long createManager) {
        this.createManager = createManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user_education.update_manager
     *
     * @return the value of pmp_user_education.update_manager
     *
     * @mbg.generated
     */
    public Long getUpdateManager() {
        return updateManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user_education.update_manager
     *
     * @param updateManager the value for pmp_user_education.update_manager
     *
     * @mbg.generated
     */
    public void setUpdateManager(Long updateManager) {
        this.updateManager = updateManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user_education.del_on
     *
     * @return the value of pmp_user_education.del_on
     *
     * @mbg.generated
     */
    public Boolean getDelOn() {
        return delOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user_education.del_on
     *
     * @param delOn the value for pmp_user_education.del_on
     *
     * @mbg.generated
     */
    public void setDelOn(Boolean delOn) {
        this.delOn = delOn;
    }
}