package com.arz.pmp.base.entity;

/**
 * Database Table Remarks:
 *   学员信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pmp_user
 */
public class PmpUserEntity {
    /**
     * Database Column Remarks:
     *   用户表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   学历信息表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.education_id
     *
     * @mbg.generated
     */
    private Long educationId;

    /**
     * Database Column Remarks:
     *   付款方式信息表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.pay_id
     *
     * @mbg.generated
     */
    private Long payId;

    /**
     * Database Column Remarks:
     *   开课班级信息表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.room_id
     *
     * @mbg.generated
     */
    private Long roomId;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   性别（0、女，1、男）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.gender
     *
     * @mbg.generated
     */
    private Boolean gender;

    /**
     * Database Column Remarks:
     *   民族
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.nationality
     *
     * @mbg.generated
     */
    private String nationality;

    /**
     * Database Column Remarks:
     *   出生时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.birthday
     *
     * @mbg.generated
     */
    private Long birthday;

    /**
     * Database Column Remarks:
     *   联系电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.phone_no
     *
     * @mbg.generated
     */
    private String phoneNo;

    /**
     * Database Column Remarks:
     *   固定电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.fixed_telephone
     *
     * @mbg.generated
     */
    private String fixedTelephone;

    /**
     * Database Column Remarks:
     *   联系邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   备用邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.backup_email
     *
     * @mbg.generated
     */
    private String backupEmail;

    /**
     * Database Column Remarks:
     *   微信号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.wechat_no
     *
     * @mbg.generated
     */
    private String wechatNo;

    /**
     * Database Column Remarks:
     *   QQ号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     * Database Column Remarks:
     *   身份证号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.identity_no
     *
     * @mbg.generated
     */
    private String identityNo;

    /**
     * Database Column Remarks:
     *   邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.zip_code
     *
     * @mbg.generated
     */
    private String zipCode;

    /**
     * Database Column Remarks:
     *   通讯地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.user_address
     *
     * @mbg.generated
     */
    private String userAddress;

    /**
     * Database Column Remarks:
     *   毕业时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.graduation_time
     *
     * @mbg.generated
     */
    private Long graduationTime;

    /**
     * Database Column Remarks:
     *   毕业学校
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.graduation_school
     *
     * @mbg.generated
     */
    private String graduationSchool;

    /**
     * Database Column Remarks:
     *   所学专业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.school_major
     *
     * @mbg.generated
     */
    private String schoolMajor;

    /**
     * Database Column Remarks:
     *   从事行业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.industry
     *
     * @mbg.generated
     */
    private String industry;

    /**
     * Database Column Remarks:
     *   公司名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.com_name
     *
     * @mbg.generated
     */
    private String comName;

    /**
     * Database Column Remarks:
     *   公司部门名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.com_department
     *
     * @mbg.generated
     */
    private String comDepartment;

    /**
     * Database Column Remarks:
     *   公司职位名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.com_position
     *
     * @mbg.generated
     */
    private String comPosition;

    /**
     * Database Column Remarks:
     *   发票抬头
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.invoice_header
     *
     * @mbg.generated
     */
    private String invoiceHeader;

    /**
     * Database Column Remarks:
     *   发票税号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.invoice_code
     *
     * @mbg.generated
     */
    private String invoiceCode;

    /**
     * Database Column Remarks:
     *   学员类型（1、内部学员，2、外部续证学员，3、联系中未报名）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.user_type
     *
     * @mbg.generated
     */
    private Integer userType;

    /**
     * Database Column Remarks:
     *   课程顾问
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.admin_id
     *
     * @mbg.generated
     */
    private Long adminId;

    /**
     * Database Column Remarks:
     *   课程信息表ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.course_id
     *
     * @mbg.generated
     */
    private Long courseId;

    /**
     * Database Column Remarks:
     *   结业状态（0、未知，1、通过，2、未通过，3、缓考，4、缓读）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.graduation_status
     *
     * @mbg.generated
     */
    private Integer graduationStatus;

    /**
     * Database Column Remarks:
     *   证书号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.cert_no
     *
     * @mbg.generated
     */
    private String certNo;

    /**
     * Database Column Remarks:
     *   证书用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.cert_user_name
     *
     * @mbg.generated
     */
    private String certUserName;

    /**
     * Database Column Remarks:
     *   证书密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.cert_password
     *
     * @mbg.generated
     */
    private String certPassword;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.create_manager
     *
     * @mbg.generated
     */
    private Long createManager;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.update_manager
     *
     * @mbg.generated
     */
    private Long updateManager;

    /**
     * Database Column Remarks:
     *   删除状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pmp_user.del_on
     *
     * @mbg.generated
     */
    private Boolean delOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.user_id
     *
     * @return the value of pmp_user.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.user_id
     *
     * @param userId the value for pmp_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.education_id
     *
     * @return the value of pmp_user.education_id
     *
     * @mbg.generated
     */
    public Long getEducationId() {
        return educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.education_id
     *
     * @param educationId the value for pmp_user.education_id
     *
     * @mbg.generated
     */
    public void setEducationId(Long educationId) {
        this.educationId = educationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.pay_id
     *
     * @return the value of pmp_user.pay_id
     *
     * @mbg.generated
     */
    public Long getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.pay_id
     *
     * @param payId the value for pmp_user.pay_id
     *
     * @mbg.generated
     */
    public void setPayId(Long payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.room_id
     *
     * @return the value of pmp_user.room_id
     *
     * @mbg.generated
     */
    public Long getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.room_id
     *
     * @param roomId the value for pmp_user.room_id
     *
     * @mbg.generated
     */
    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.user_name
     *
     * @return the value of pmp_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.user_name
     *
     * @param userName the value for pmp_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.gender
     *
     * @return the value of pmp_user.gender
     *
     * @mbg.generated
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.gender
     *
     * @param gender the value for pmp_user.gender
     *
     * @mbg.generated
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.nationality
     *
     * @return the value of pmp_user.nationality
     *
     * @mbg.generated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.nationality
     *
     * @param nationality the value for pmp_user.nationality
     *
     * @mbg.generated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.birthday
     *
     * @return the value of pmp_user.birthday
     *
     * @mbg.generated
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.birthday
     *
     * @param birthday the value for pmp_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.phone_no
     *
     * @return the value of pmp_user.phone_no
     *
     * @mbg.generated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.phone_no
     *
     * @param phoneNo the value for pmp_user.phone_no
     *
     * @mbg.generated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.fixed_telephone
     *
     * @return the value of pmp_user.fixed_telephone
     *
     * @mbg.generated
     */
    public String getFixedTelephone() {
        return fixedTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.fixed_telephone
     *
     * @param fixedTelephone the value for pmp_user.fixed_telephone
     *
     * @mbg.generated
     */
    public void setFixedTelephone(String fixedTelephone) {
        this.fixedTelephone = fixedTelephone == null ? null : fixedTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.email
     *
     * @return the value of pmp_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.email
     *
     * @param email the value for pmp_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.backup_email
     *
     * @return the value of pmp_user.backup_email
     *
     * @mbg.generated
     */
    public String getBackupEmail() {
        return backupEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.backup_email
     *
     * @param backupEmail the value for pmp_user.backup_email
     *
     * @mbg.generated
     */
    public void setBackupEmail(String backupEmail) {
        this.backupEmail = backupEmail == null ? null : backupEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.wechat_no
     *
     * @return the value of pmp_user.wechat_no
     *
     * @mbg.generated
     */
    public String getWechatNo() {
        return wechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.wechat_no
     *
     * @param wechatNo the value for pmp_user.wechat_no
     *
     * @mbg.generated
     */
    public void setWechatNo(String wechatNo) {
        this.wechatNo = wechatNo == null ? null : wechatNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.qq
     *
     * @return the value of pmp_user.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.qq
     *
     * @param qq the value for pmp_user.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.identity_no
     *
     * @return the value of pmp_user.identity_no
     *
     * @mbg.generated
     */
    public String getIdentityNo() {
        return identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.identity_no
     *
     * @param identityNo the value for pmp_user.identity_no
     *
     * @mbg.generated
     */
    public void setIdentityNo(String identityNo) {
        this.identityNo = identityNo == null ? null : identityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.zip_code
     *
     * @return the value of pmp_user.zip_code
     *
     * @mbg.generated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.zip_code
     *
     * @param zipCode the value for pmp_user.zip_code
     *
     * @mbg.generated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.user_address
     *
     * @return the value of pmp_user.user_address
     *
     * @mbg.generated
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.user_address
     *
     * @param userAddress the value for pmp_user.user_address
     *
     * @mbg.generated
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.graduation_time
     *
     * @return the value of pmp_user.graduation_time
     *
     * @mbg.generated
     */
    public Long getGraduationTime() {
        return graduationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.graduation_time
     *
     * @param graduationTime the value for pmp_user.graduation_time
     *
     * @mbg.generated
     */
    public void setGraduationTime(Long graduationTime) {
        this.graduationTime = graduationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.graduation_school
     *
     * @return the value of pmp_user.graduation_school
     *
     * @mbg.generated
     */
    public String getGraduationSchool() {
        return graduationSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.graduation_school
     *
     * @param graduationSchool the value for pmp_user.graduation_school
     *
     * @mbg.generated
     */
    public void setGraduationSchool(String graduationSchool) {
        this.graduationSchool = graduationSchool == null ? null : graduationSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.school_major
     *
     * @return the value of pmp_user.school_major
     *
     * @mbg.generated
     */
    public String getSchoolMajor() {
        return schoolMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.school_major
     *
     * @param schoolMajor the value for pmp_user.school_major
     *
     * @mbg.generated
     */
    public void setSchoolMajor(String schoolMajor) {
        this.schoolMajor = schoolMajor == null ? null : schoolMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.industry
     *
     * @return the value of pmp_user.industry
     *
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.industry
     *
     * @param industry the value for pmp_user.industry
     *
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.com_name
     *
     * @return the value of pmp_user.com_name
     *
     * @mbg.generated
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.com_name
     *
     * @param comName the value for pmp_user.com_name
     *
     * @mbg.generated
     */
    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.com_department
     *
     * @return the value of pmp_user.com_department
     *
     * @mbg.generated
     */
    public String getComDepartment() {
        return comDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.com_department
     *
     * @param comDepartment the value for pmp_user.com_department
     *
     * @mbg.generated
     */
    public void setComDepartment(String comDepartment) {
        this.comDepartment = comDepartment == null ? null : comDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.com_position
     *
     * @return the value of pmp_user.com_position
     *
     * @mbg.generated
     */
    public String getComPosition() {
        return comPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.com_position
     *
     * @param comPosition the value for pmp_user.com_position
     *
     * @mbg.generated
     */
    public void setComPosition(String comPosition) {
        this.comPosition = comPosition == null ? null : comPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.invoice_header
     *
     * @return the value of pmp_user.invoice_header
     *
     * @mbg.generated
     */
    public String getInvoiceHeader() {
        return invoiceHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.invoice_header
     *
     * @param invoiceHeader the value for pmp_user.invoice_header
     *
     * @mbg.generated
     */
    public void setInvoiceHeader(String invoiceHeader) {
        this.invoiceHeader = invoiceHeader == null ? null : invoiceHeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.invoice_code
     *
     * @return the value of pmp_user.invoice_code
     *
     * @mbg.generated
     */
    public String getInvoiceCode() {
        return invoiceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.invoice_code
     *
     * @param invoiceCode the value for pmp_user.invoice_code
     *
     * @mbg.generated
     */
    public void setInvoiceCode(String invoiceCode) {
        this.invoiceCode = invoiceCode == null ? null : invoiceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.user_type
     *
     * @return the value of pmp_user.user_type
     *
     * @mbg.generated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.user_type
     *
     * @param userType the value for pmp_user.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.admin_id
     *
     * @return the value of pmp_user.admin_id
     *
     * @mbg.generated
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.admin_id
     *
     * @param adminId the value for pmp_user.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.course_id
     *
     * @return the value of pmp_user.course_id
     *
     * @mbg.generated
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.course_id
     *
     * @param courseId the value for pmp_user.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.graduation_status
     *
     * @return the value of pmp_user.graduation_status
     *
     * @mbg.generated
     */
    public Integer getGraduationStatus() {
        return graduationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.graduation_status
     *
     * @param graduationStatus the value for pmp_user.graduation_status
     *
     * @mbg.generated
     */
    public void setGraduationStatus(Integer graduationStatus) {
        this.graduationStatus = graduationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.cert_no
     *
     * @return the value of pmp_user.cert_no
     *
     * @mbg.generated
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.cert_no
     *
     * @param certNo the value for pmp_user.cert_no
     *
     * @mbg.generated
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.cert_user_name
     *
     * @return the value of pmp_user.cert_user_name
     *
     * @mbg.generated
     */
    public String getCertUserName() {
        return certUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.cert_user_name
     *
     * @param certUserName the value for pmp_user.cert_user_name
     *
     * @mbg.generated
     */
    public void setCertUserName(String certUserName) {
        this.certUserName = certUserName == null ? null : certUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.cert_password
     *
     * @return the value of pmp_user.cert_password
     *
     * @mbg.generated
     */
    public String getCertPassword() {
        return certPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.cert_password
     *
     * @param certPassword the value for pmp_user.cert_password
     *
     * @mbg.generated
     */
    public void setCertPassword(String certPassword) {
        this.certPassword = certPassword == null ? null : certPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.remark
     *
     * @return the value of pmp_user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.remark
     *
     * @param remark the value for pmp_user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.create_time
     *
     * @return the value of pmp_user.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.create_time
     *
     * @param createTime the value for pmp_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.update_time
     *
     * @return the value of pmp_user.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.update_time
     *
     * @param updateTime the value for pmp_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.create_manager
     *
     * @return the value of pmp_user.create_manager
     *
     * @mbg.generated
     */
    public Long getCreateManager() {
        return createManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.create_manager
     *
     * @param createManager the value for pmp_user.create_manager
     *
     * @mbg.generated
     */
    public void setCreateManager(Long createManager) {
        this.createManager = createManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.update_manager
     *
     * @return the value of pmp_user.update_manager
     *
     * @mbg.generated
     */
    public Long getUpdateManager() {
        return updateManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.update_manager
     *
     * @param updateManager the value for pmp_user.update_manager
     *
     * @mbg.generated
     */
    public void setUpdateManager(Long updateManager) {
        this.updateManager = updateManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pmp_user.del_on
     *
     * @return the value of pmp_user.del_on
     *
     * @mbg.generated
     */
    public Boolean getDelOn() {
        return delOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pmp_user.del_on
     *
     * @param delOn the value for pmp_user.del_on
     *
     * @mbg.generated
     */
    public void setDelOn(Boolean delOn) {
        this.delOn = delOn;
    }
}