package com.arz.pmp.base.mapper;

import com.arz.pmp.base.entity.PmpAdminEntity;

public interface PmpAdminEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_admin
     *
     * @mbg.generated
     */
    int insert(PmpAdminEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_admin
     *
     * @mbg.generated
     */
    int insertSelective(PmpAdminEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_admin
     *
     * @mbg.generated
     */
    PmpAdminEntity selectByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmpAdminEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmpAdminEntity record);
}