package com.arz.pmp.base.mapper;

import com.arz.pmp.base.entity.PmpCourseEntity;

public interface PmpCourseEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_course
     *
     * @mbg.generated
     */
    int insert(PmpCourseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_course
     *
     * @mbg.generated
     */
    int insertSelective(PmpCourseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_course
     *
     * @mbg.generated
     */
    PmpCourseEntity selectByPrimaryKey(Long courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmpCourseEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmpCourseEntity record);
}