package com.arz.pmp.base.mapper;

import com.arz.pmp.base.entity.PmpPermissionEntity;

public interface PmpPermissionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long permId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_permission
     *
     * @mbg.generated
     */
    int insert(PmpPermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_permission
     *
     * @mbg.generated
     */
    int insertSelective(PmpPermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_permission
     *
     * @mbg.generated
     */
    PmpPermissionEntity selectByPrimaryKey(Long permId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmpPermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmpPermissionEntity record);
}