package com.arz.pmp.base.mapper;

import com.arz.pmp.base.entity.PmpRoleEntity;

public interface PmpRoleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role
     *
     * @mbg.generated
     */
    int insert(PmpRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role
     *
     * @mbg.generated
     */
    int insertSelective(PmpRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role
     *
     * @mbg.generated
     */
    PmpRoleEntity selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmpRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmpRoleEntity record);
}