package com.arz.pmp.base.mapper;

import com.arz.pmp.base.entity.PmpRolePermissionEntity;

public interface PmpRolePermissionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role_permission
     *
     * @mbg.generated
     */
    int insert(PmpRolePermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(PmpRolePermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role_permission
     *
     * @mbg.generated
     */
    PmpRolePermissionEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmpRolePermissionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_role_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmpRolePermissionEntity record);
}