package com.arz.pmp.base.mapper;

import com.arz.pmp.base.entity.PmpSystemLogEntity;

public interface PmpSystemLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_system_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_system_log
     *
     * @mbg.generated
     */
    int insert(PmpSystemLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_system_log
     *
     * @mbg.generated
     */
    int insertSelective(PmpSystemLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_system_log
     *
     * @mbg.generated
     */
    PmpSystemLogEntity selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_system_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmpSystemLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_system_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PmpSystemLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_system_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmpSystemLogEntity record);
}