package com.arz.pmp.base.mapper;

import com.arz.pmp.base.entity.PmpTeachingRoomEntity;

public interface PmpTeachingRoomEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_teaching_room
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_teaching_room
     *
     * @mbg.generated
     */
    int insert(PmpTeachingRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_teaching_room
     *
     * @mbg.generated
     */
    int insertSelective(PmpTeachingRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_teaching_room
     *
     * @mbg.generated
     */
    PmpTeachingRoomEntity selectByPrimaryKey(Long roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_teaching_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmpTeachingRoomEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_teaching_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmpTeachingRoomEntity record);
}