package com.arz.pmp.base.mapper;

import com.arz.pmp.base.entity.PmpUserEntity;

public interface PmpUserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_user
     *
     * @mbg.generated
     */
    int insert(PmpUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_user
     *
     * @mbg.generated
     */
    int insertSelective(PmpUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_user
     *
     * @mbg.generated
     */
    PmpUserEntity selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmpUserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pmp_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmpUserEntity record);
}